### ISSUE TITLE
Accessibility Support

### ISSUE THREAD

**Issue by krymancer** [alohe/emojicloud#6]
Hi, nice repo, find it from the dev.to post

I think is nice to add [aria support](https://www.w3.org/TR/SVG/access.html) once the major browsers already support and a good part of screen readers too.

 The svgs are gonna to look like this: 
```
<svg aria-labelledby="title  desc">
   <title id="title">Circle</title>
   <desc id="desc">Red Circle</desc>
   <circle role="presentation" cy="60" r="55"  fill="red" />
</svg>
```

We can automate this process once system defaults emojis already have descriptions so once we gather this information a simple script can inject the title and description in the svgs

**Comment by alohe** [comment]
```
<svg aria-label="Airplane emoji">
...
</svg>
```
I've added **aria-label** with the emoji name as its value
